### ISSUE TITLE
Performance Doubt

### ISSUE THREAD

**Issue by willsilvano** [bayespy/bayespy#111]
Hello friends!

I would like to try out the **bayespy** library, however my question is if there is any kind of performance problem in predicting Bayesian networks with many records?

I'm using another library that also works with Bayesian networks and performs prediction based on observations sent to the network, but I'm having performance issues, and it takes 1 second to predict each record.

My initial database contains 100k + records, so I need something that is as performative as possible.

Thank you!

**Comment by jluttine** [comment]
Can you give some details about the model you're constructing? Otherwise it's difficult to say because Bayesian network means basically any Bayesian model (that's constructed from conditional distributions). Certainly, there are models for which current BayesPy nodes don't provide very efficient code without perhaps writing some pieces manually.

**Comment by willsilvano** [comment]
Hello Friend.

The model of my Bayesian network basically works with discretized data, for example variable sex (M, F).

Currently I have about 50 variables for each record, all of them discretized can have 2 or more values, for example variable occupational situation (Employee, Unemployed, Seeking first job, Retired, Self employed, etc.)

**Comment by jluttine** [comment]
Ok! Current release of BayesPy provides very poor support for discrete categorical graphs. This is because one needs to construct with mixture distributions and get mean-field approximation where all variables are assumed independent. This is really bad.

Fortunately, there is currently work going on for adding proper support for such models! This is a bit work in progress, but it currently supports graphs of categorical variables and exact efficient inference on those  by using the junction tree algorithm. See this recent comment for more details: https://github.com/bayespy/bayespy/issues/37#issuecomment-377966348

I would be interested to hear about your experience if you try it out. If you notice any issues, we can try to solve them and implement any missing features.
