### ISSUE TITLE
Anaconda install of bayespy causes a downgrade of ipython

### ISSUE THREAD

**Issue by texadactyl** [bayespy/bayespy#117]
It's true that ipython 7.3 to 7.6 caused some distracting error messages.  In ipython 7.7, this has been fixed.  Please stop causing the downgrade of ipython to 7.2 as a result of installing bayespy since this is no longer an issue.

Thank you.

**Comment by jluttine** [comment]
I don't know anything about this. I don't see anything in `setup.py` that would cause this (https://github.com/bayespy/bayespy/blob/develop/setup.py#L48). Probably this is related to BayesPy packaging in conda-forge. Perhaps @volpatto has some insight (because of https://github.com/bayespy/bayespy/pull/116)?

**Comment by volpatto** [comment]
Sure, I will take a look and return here with a feedback.

**Comment by volpatto** [comment]
@texadactyl this is strange, because there is no direct dependency between `bayespy` and `ipython`. I send a fix to conda-forge. I will pin the `ipython` version to 7.7 or above.

**Comment by volpatto** [comment]
The package is updated, you can check it [here](https://anaconda.org/conda-forge/bayespy). Now just wait for anaconda servers to update and you can install it in your env with

```
conda install -c conda-forge bayespy
```

If the downgrade problem is not solved, please ping me.

**Comment by texadactyl** [comment]
I just did a conda update and it did not happen this time.  I cannot explain what happened yesterday and I hope that I didn't put you on a wild goose chase.

**Comment by volpatto** [comment]
@texadactyl That's OK! This is the kind of stuff that conda-forge package maintainers are up to. 

I'm a little concerned about pinning `ipython>=7.7` in the conda-forge. Maybe this can generate problem for users that have an env with several packages. Some compatibility issues can rise due to the pin, but I'll wait. No optimizations have to be employed before the need. 

Again, if you face any problem about `ipython` and `bayespy`, just ping me in an issue!
