### ISSUE TITLE
Using the posterior distribution?

### ISSUE THREAD

**Issue by multimeric** [bayespy/bayespy#123]
Hi, I'm interested in using bayespy to infer a posterior, and then use it to evaluate the predictive distribution, or else a MAP estimate if that isn't possible. Can this be done?

**Comment by jluttine** [comment]
Hi! Yep, BayesPy infers an approximate posterior distribution. See docs for details:

- https://www.bayespy.org/user_guide/quickstart.html
- https://www.bayespy.org/user_guide/plot.html#posterior-parameters-and-moments

In order to make predictions, you can create a model which contains both the things you observer and the things you want to predict. Then, you'll get the posterior distribution of the things you want to predict too. Alternatively, you can first fit a model for the observations and fit it. After that, re-use the parameter nodes you want in a new predictive model.
