### ISSUE TITLE
GaussianARD in SumMultiply

### ISSUE THREAD

**Issue by azane** [bayespy/bayespy#27]
##### Hello!
First, a disclaimer, bayesian inference is still quite fuzzy to me, so I may have some foundational misunderstandings that render this question moot.
Also, this is my attempt at going beyond the linear regression example in the docs, so I may have stumbled there as well.
That known though, let's carry on! : )

##### The Big Picture
I *believe* this is irrelevant to my problem, but it may highlight some potential misunderstandings of mine, so I will include it. Further, this may be a silly thing to attempt with bayespy. If so, please shoo me out the door. : )
I am trying to fit some data, over a small range in multidimensional space, in the most flexible way possible. Because data at infinity is well outside the relevant range, I've chosen a standard polynomial model. For now, I am pre-calculating the value of each term combination to its respective degree, but that is not included below. Below, I have an arbitrary set of input data "after" the term multiplication and exponent...iation [;)] has been executed. 
The first axis of the array is the degree of the term, the second axis differentiates the variable subsets, and the third axis is the value of the term after having the subset multiplied together and being raised to the exponent. The complication is mostly to keep the terms straight in my head. : )

##### The Specifics
So, I only want to infer the beta values in an array of shape ```(n, c) #(degree of polynomial, number of combinations)```. From my hazy understanding, I believe this is accomplished by passing the shape tuple to the plates argument. When I call ```print(b.random())``` it does reveal the expected shape.
Further, the numpy einsum version of what I pass to ```SumMultiply``` returns the expected results.
But, SumMultiply complains, via dot.py, that the dimension of ```b``` is 0, despite ```b.random()``` returning the expected shape.
I tried specifying the ```ndims``` argument of ```GaussianARD```, which gets it past the error, but that seems to *add* those dimensions to the specified shape, and the resulting output fails to line up with the dependent data. I will include the code/output of this if asked.

Again, the snippet below is the simplest version I could write to reproduce the error. Thanks for any and all help!

##### Code
```python
import bayespy as bp
import numpy as np


n = 3 #the degree of the polynomial to be fitted
t = 3 #the number of dimensions in the independent data
s = 30 #the size each dimension of independent data.

c = 2**t #the number of possible subsets, or combinations,, given the number of terms.

x = np.random.normal(0, 1, (n, c, s)) #arbitrary independent data

b = bp.nodes.GaussianARD(0, 1e-3, plates=(n, c))

print(np.einsum('ij,ijk', b.random(), x))

f = bp.nodes.SumMultiply('ij,ijk', b, x)

```

##### Output
```
[ 352.13537754    6.74444895  230.50129002   26.89123883  -29.92484017
  -33.0472705   137.11028844  112.22195238   -1.93933497 -114.03582012
  -47.26830425 -117.52203611  -16.49295875    8.54611721  147.28272235
  227.64725706 -389.12665218  172.95347527  158.56884408  -31.35686066
 -330.38439688  132.03443101 -251.77565183  178.87004007 -201.6372575
  -91.99130081 -243.31541085   43.45470217  260.13981808  103.8843901 ]
Traceback (most recent call last):
  File "spider/py3/tshoot.py", line 17, in <module>
    f = bp.nodes.SumMultiply('ij,ijk', b, x)
  File "/usr/local/lib/python3.5/site-packages/bayespy/inference/vmp/nodes/dot.py", line 210, in __init__
    len(nodes[n].dims[0])))
ValueError: Wrong number of keys (2) for the node number 0 with 0 dimensions
```

**Comment by jluttine** [comment]
Thanks for the message and for the very clearly written code example! :) Just a minor change to your code should fix the problem.

To understand the problem, you need to know that BayesPy considers Gaussian variables to have both `shape` and `plates`. `shape` defines the "shape" of the Gaussian variable and `plates` defines the "repetition" of these variables. `plates` defines sets that are independent in the posterior while `shape` defines the shape of the variable array in which elements are correlated in the posterior approximation. In your case, you want to (or need to) model the correlations on those axes that are summed over, thus you want to define those as `shape` axes and the non-summed axes as `plates` axes. May sound a bit complicated, especially if you're not familiar with variational Bayesian methods..

Anyway, this should fix your code:
```
b = bp.nodes.GaussianARD(0, 1e-3, shape=(n, c))  # use shape, not plates
```

However, I suppose you don't want to sum over axis `s`, so you need to modify the code a bit more to avoid that summing. There might be a slight difference to `einsum` because that key definition you used would sum over `s` axis in `SumMultiply`. So, if you don't want to sum over that axis, you need to change the code as follows:
```
x = np.random.normal(0, 1, (s, n, c)) # move s axis to be the first
b = bp.nodes.GaussianARD(0, 1e-3, shape=(n, c))
f = bp.nodes.SumMultiply('ij,ij', b, x)  # ignore s axis in the keys
```
The total shape of a `GaussianARD` variable is `plates + shape`, thus the `shape` axes are the trailing axes. Notice that I just moved `s` axes to be the first axis and the summed axes `n` and `c` are the last axes. In addition, `SumMultiply` can sum only `shape` axes, not `plates` axes. I can try to explain this `plates` and `shape` difference in more detail if you want. It can be a bit confusing.

Then a general comment about your approach if you're interested. :) Using a high-order polynomial to gain flexibility isn't the best way to go. You limit the possible functions to only those functions that are represented as such polynomials. I would suggest you consider Gaussian processes for the task, if you find yourself comfortable with them. They are an amazing tool for flexible non-linear regression problems using the Bayesian approach. GPs aren't yet implemented in BayesPy but they are available for instance in GPy https://github.com/SheffieldML/GPy or pyGPs https://github.com/marionmari/pyGPs or a few other toolboxes. Just a thought. But if you want to do polynomial regression, then your approach with BayesPy is good. :)

The regression code may not scale to very large datasets because of how BayesPy handles messages internally, but I hope you won't be affected by that problem. Just letting you know if you happen to hit that problem with bigger datasets that you think should be easily inside the computational limits.

Did this help? Please don't hesitate to ask further questions.

**Comment by azane** [comment]
Thanks so much for the prompt and most helpful response! Those additions/changes did the trick; and the high order polynomial method successfully modeled this round of test data.
I *think* I understand the plates-shape differentiation, at least enough to refresh my memory next time. Looking back at the linear regression example, I see that ```shape``` is very clearly used, and not ```plates```. Oops. : /
I still haven't quite wrapped my mind around Einstein summation...in general, so I will have to re-watch that Einstein summation playlist on youtube. ; )

Your comment on the general approach is most welcome. Per your suggestion, I looked into Gaussian processes, and they look like the ticket! But I have a question: part of the reason I wanted to use high order polynomials is because I can easily take their derivatives programatically. Zooming out even more, I am working on a reinforcement learning model where the learner attempts to climb the gradient to maximize the dependent value, so I'll need the derivative (possibly the second, third, etc.) of the inferred model. So...how difficult is it to compute the gradient of a Gaussian process model?

Thanks again for the help!

**Comment by jluttine** [comment]
About GP derivatives, see section 9.4 in Gaussian Processes for Machine Learning (Rasmussen & Williams), available here: http://www.gaussianprocess.org/gpml/chapters/RW9.pdf . (Great book, I recommend you take a look at it.) In short, "since differentiation is a linear operator, the derivative of a Gaussian process is another Gaussian process". You just basically use the derivative of your covariance function as the covariance function of your derivative. Simple. So you not only get a posterior distribution over functions but also a posterior distribution over the derivative (and even higher order derivatives). I'm not sure how easily the packages I mentioned support this kind of operation, but in any case it should be relatively easy and straightforward to implement derivatives of covariance functions yourself. Cheers! :)

**Comment by azane** [comment]
Wow! Thanks for the above-and-beyond assistance! That is a great resource saying exactly what I wanted to hear; looks like I have my work cut out for me.
Thanks for pointing me in the right direction. : )
