### ISSUE TITLE
Mixture of parents

### ISSUE THREAD

**Issue by jazzmes** [bayespy/bayespy#33]
Hi, 

Congrats on your project. I really like how you organized it.
I am a relative beginner to belief and bayesian networks but I found the documentation and the examples to be relatively easy to understand.
However, I got stuck trying to create a node that might even be a simple one: create a mixture distribution of parents. 

I have a set of nodes that result from linear combination of gaussian nodes. Then, I created a new node that would be a simple mixture of the that set of nodes. At first, the Mixture node seemed an obvious choice but the examples in the documentation assume generic Gaussians (or other distributions) and could not understand how to use it when you already have parent nodes. 

I also saw from #23 that you can combine several parent nodes in a Mixture node, but could not figure out how to combine to achieve my goal. I could have a the initial argument of the Mixture be the distribution of the clusters, but could not understand how to set the parents.

I sketched and attached a plate notation graphic model figure to try to help explain my goal.
![gm](https://cloud.githubusercontent.com/assets/1198464/11450133/7ebdfa8c-9547-11e5-9372-9456199efe48.png)
In the figure I have an extra observed node that is a simple sum of the parents. I am trying to figure out how to implement the T^s nodes. I am still exploring different models, and understand how fast it might converge with my data.

Could you provide an example how to do this, if it is possible? Or point me to a point in the documentation that explains this example?
Let me know if I need to make my question more clear and thank you for your time and help!

**Comment by jluttine** [comment]
Hi, and thanks for the feedback! I'd be happy to help, but unfortunately I'm having difficulties trying to interpret that plate notation into equations. Could you write your model as equations (conditional probability distributions)? Or at least that part which is relevant to your question. That'd be great.

**Comment by jazzmes** [comment]
Sorry about that! Should have started with a simpler explanation specially as I am still shaky when using the plates notation.

Consider a random variable Y with parents {X_i} Y will take the value of the X_i with probability p_i. On the other hand, each X_i results from a SumMultiply operation between a weight vector, w and an observed vector r that we assume to be gaussian

![gm2](https://cloud.githubusercontent.com/assets/1198464/11478691/627d70b6-9743-11e5-913f-b98cdb60b17a.png)

And, ... 
![eq](https://cloud.githubusercontent.com/assets/1198464/11478657/3a2f359a-9743-11e5-8e5a-bf4b57231048.png)

After writing this, i though I could create a mixture of SumMultiply nodes, something like...
```python
alpha = Dirichlet([1e-3] * M)
mu = []
tau = []
for i in range(N):

Y = Mixture(Categorical(alpha), SumMultiply, 'i,i', w, Gaussian(mu, tau), SumMultiply, ...)
```
but i guess that is not possible to create that kind of mixture.

**Comment by jluttine** [comment]
NOTE: This message is available as Jupyter Notebook in https://github.com/bayespy/bayespy-notebooks/blob/master/notebooks/issue33.ipynb and can be run interactively in Binder: [![Binder](http://mybinder.org/badge.svg)](http://mybinder.org/repo/bayespy/bayespy-notebooks/notebooks/issue33.ipynb)

Thanks a lot for the simplification! The problem is that the distribution type of `Mixture` must be a distribution, not a deterministic operation. Here you seem to want `Y` to be a mixture of Gaussians, with mean `X` and precision `1/sigma**2`. You should define `X` with `SumMultiply`, but `Y` as a Gaussian mixture.

First, define the cluster assignments:


```python
from bayespy.nodes import Dirichlet, Categorical
N = 40 # number of data samples
M = 3 # number of clusters (i.e., mixture components)
alpha = Dirichlet([1e-3] * M) # cluster probabilities or "sizes"
theta = Categorical(alpha, plates=(N,)) # assignment for each data sample
```

As you observe `r`, is it necessary to give it Gaussian prior? Is it sufficient just to fix it, or do you specifically want to estimate its distribution? I'll assume here that `r` is just some inputs you can use as fixed values. Also, which of your variables `w` and `r` have cluster-specific values? I assume you want to learn different weight vectors `w` for clusters but each input `r` doesn't depend on the cluster. I might be guessing wrong here, so you may need to fix these snippets accordingly. I also assume that `w` is the same for each data sample but `r` is sample-specific. These assumptions affect how I use the plates for `w` and `r`. Easy to change if I have made wrong assumptions.


```python
from bayespy.nodes import Gaussian, SumMultiply
p = 5 # dimensionality fo w and r
import numpy as np
w = Gaussian(np.zeros(p), 1e-3*np.identity(p), plates=(1,M)) # weight vectors, no sample plate
r = np.random.randn(N, 1, p)  # fixed inputs, no cluster plate
X = SumMultiply('i,i->', w, r)
```

Construct the mixture distribution. Again, do you want to have shared or different precision parameter for each cluster? Here I assume different, but that can be modified in the plates.


```python
from bayespy.nodes import Mixture, Gamma, GaussianARD
tau = Gamma(1e-3, 1e-3, plates=(M,)) # Do you want to have different precision for each cluster?
Y = Mixture(theta, GaussianARD, X, tau)
```

Just some random data generated with two different weight vectors:


```python
data1 = np.einsum('...i,...i->...', np.random.randn(p), r)
data2 = np.einsum('...i,...i->...', np.random.randn(p), r)
data = np.where(np.random.rand(N, 1)>0.5, data1, data2)[:,0]
Y.observe(data)
```

Break the symmetry in the model in order to not converge to a bad trivial solution:


```python
theta.initialize_from_random()
```

Create the inference engine:


```python
from bayespy.inference import VB
Q = VB(Y, w, tau, theta, alpha)
```

Run VB algorithm:


```python
Q.update(repeat=200)
```

Now you can use the results. For instance, plot the cluster assignments for each sample:


```python
%matplotlib inline
import bayespy.plot as bpplt
bpplt.hinton(theta)
```

Or plot the weight vectors for each cluster:


```python
bpplt.hinton(w)
```

Does this answer your question? :) I can give more details on some steps if you like. Also, if I misunderstood something (or everything) please correct me. :)

**Comment by jazzmes** [comment]
Hi, thank you so much for writing such a long and complete response.

Your answer is very similar to my initial thoughts of how to do it. In the end, the key detail was in the definition of ```Y```, where you used ```X``` as the mean parameter of the mixture of gaussians, with an extra ```tau``` parameter for the precision
```python
Y = Mixture(theta, GaussianARD, X, tau)
```

Regarding your question:
"As you observe r, is it necessary to give it Gaussian prior? Is it sufficient just to fix it, or do you specifically want to estimate its distribution?" 
Yes, I want to estimate the distribution of ```r``` so that I can also compute the distribution of the intermediate ```X``` variables. I am assuming I can just modify ```r``` to be a gaussian node...
Most of your other assumptions were either correct, or I'll make the necessary plates adjustments.

Anyway, thank you so much for your clarifications. I should be able to take it from here! :)
