### ISSUE TITLE
Trying to learn LDA collapsing out variables using Gradient Based Optimization throws "Not Implemented"

### ISSUE THREAD

**Issue by viveksck** [bayespy/bayespy#46]
Hi,
Thanks for the great package. I am trying to modify your LDA model code, by using gradient methods (model.optimize()) where I collapse out p_topic and p_word during inference but I  am hitting an error.

Basically, in the lda.py example you provided, I changed:
Line 126: Q.update(repeat=300) to the below
126         Q.update(repeat=1)
127         Q.optimize('topics', maxiter=300, collapsed=['p_topic', 'p_word'])  # Collapsing p_topic and p_word as we only need individual topic assignments to each word

However I get the following error: "NotImplementedError: Standard gradient not yet implemented for CategoricalDistribution".  Is it possible to use BayesPy's advanced methods that support collapsing out variables for models like LDA? 

See call stack:
```python
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-13b3b051706b> in <module>()
----> 1 Q = run(n_documents=100, n_topics=2, n_vocabulary=2, seed=1)

/home/vasant/bayespyexp/lda.py in run(n_documents, n_topics, n_vocabulary, n_words, stochastic, maxiter, seed)
    125 
    126         Q.update(repeat=1)
--> 127         Q.optimize('topics', maxiter=300, collapsed=['p_topic', 'p_word'])
    128 
    129     else:

/home/vasant/.virtualenvs/mypython3/lib/python3.4/site-packages/bayespy/inference/vmp/vmp.py in optimize(self, maxiter, verbose, method, riemannian, collapsed, tol, *nodes)
    451             rg = self.get_gradients(*nodes, euclidian=False)
    452         else:
--> 453             (rg, g) = self.get_gradients(*nodes, euclidian=True)
    454 
    455         if riemannian:

/home/vasant/.virtualenvs/mypython3/lib/python3.4/site-packages/bayespy/inference/vmp/vmp.py in get_gradients(self, euclidian, *nodes)
    370         if euclidian:
    371             g = [self[node].get_gradient(rg_x)
--> 372                  for (node, rg_x) in zip(nodes, rg)]
    373             return (rg, g)
    374         else:

/home/vasant/.virtualenvs/mypython3/lib/python3.4/site-packages/bayespy/inference/vmp/vmp.py in <listcomp>(.0)
    370         if euclidian:
    371             g = [self[node].get_gradient(rg_x)
--> 372                  for (node, rg_x) in zip(nodes, rg)]
    373             return (rg, g)
    374         else:

/home/vasant/.virtualenvs/mypython3/lib/python3.4/site-packages/bayespy/inference/vmp/nodes/expfamily.py in get_gradient(self, rg)
    276         can provide it to this function to avoid re-computing it."""
    277 
--> 278         g = self._distribution.compute_gradient(rg, self.u, self.phi)
    279         for i in range(len(g)):
    280             g[i] /= self.annealing

/home/vasant/.virtualenvs/mypython3/lib/python3.4/site-packages/bayespy/inference/vmp/nodes/expfamily.py in compute_gradient(self, g, u, phi)
     65 
     66         raise NotImplementedError("Standard gradient not yet implemented for %s"
---> 67                                   % (self.__class__.__name__))
     68 
     69 

NotImplementedError: Standard gradient not yet implemented for CategoricalDistribution
```

**Comment by jluttine** [comment]
Thanks for the report. I'll take a look and get back to you.

**Comment by viveksck** [comment]
Thanks ! By the way if using pattern_search instead of optimize does not throw any error.

**Comment by jluttine** [comment]
Sorry for the delay, I finally had some time to work on this.

You are getting `NotImplementedError` because the conjugate gradient optimization requires the Euclidean gradient for the nodes that are optimized and it wasn't implemented yet for the Categorical nodes. Usually, Riemannian gradient is used and the Euclidean gradient requires a bit extra work, thus it isn't implemented for all nodes yet. But I now implemented it for the Categorical node, so I think it should work now. It's currently in the `develop` branch so you need to install that branch as, for instance:

```
pip install git+https://github.com/bayespy/bayespy.git@develop
```

I also made some other minor fixes to the optimization function. If you notice any problems, please don't hesitate to report.

I'd also like to note that the collapsing method used in BayesPy doesn't affect the posterior approximation (i.e., it doesn't give you a more accurate approximation), it just affects the learning speed basically. You may experiment do you get any significant speed-ups by using the collapsing method, but in most cases I think the standard VB-EM is quite sufficient. If you have large datasets, then I'd suggest you try stochastic variational inference which is also available in BayesPy.

Also, my intuition is that it is better to collapse `topics` and optimize `p_topic` and `p_word`. Main reasons: 1) `topics` has more variables than the others; 2) `p_topic` and `p_word` don't d-separate given `topics`, thus the collapsing isn't "exact". Thus, try something like:

```
Q.optimize('topics', maxiter=300, collapsed=['p_topic', 'p_word'])
```

If you get any insight which works best, I'd be interested to hear. I'm also planning to write a more comprehensive LDA example as a notebook in the near future.

**Comment by viveksck** [comment]
Thanks a ton ! I  will try this out soon and get back to you.

**Comment by viveksck** [comment]
Thanks ! That works. I am pasting a notebook with synthetic data verifying this.

```python

# coding: utf-8

# In[1]:

import bayespy
import numpy as np
import bayespy.plot as bpplt
from collections import Counter


# In[2]:

numTopics = 2
numWords = 4
numDocuments = 10
lenDocument = 1000


# In[3]:

def generate_data():    
    theta = np.array([[0.1, 0.9],[0.1, 0.9], [0.1, 0.9], [0.1,0.9],[0.1,0.9],
                      [0.9, 0.1],[0.9, 0.1], [0.9, 0.1], [0.9, 0.1],[0.9, 0.1]]
                    )
    phi = np.array([[0.0, 0.0, 0.5, 0.5], [0.5, 0.5, 0.0, 0.0]])
    words=[]
    for d in np.arange(0, numDocuments):
        for w in np.arange(0, lenDocument):
            chosenTopic = np.random.choice(numTopics, p=theta[d])
            chosenWord = np.random.choice(numWords, p=phi[chosenTopic])
            words.append(chosenWord)
    return np.array(words)


# In[4]:

data = generate_data()


# In[5]:

theta = bayespy.nodes.Dirichlet(np.ones(numTopics), plates=(numDocuments,))
phi = bayespy.nodes.Dirichlet(np.ones(numWords), plates=(numTopics,))


# In[6]:

word_doc_ids = []
for doc_no in np.arange(0, numDocuments):
    doc_id = np.ones(lenDocument) * doc_no
    doc_id = doc_id.astype(int)
    word_doc_ids.extend(doc_id)


# In[7]:

z = bayespy.nodes.Categorical(bayespy.nodes.Gate(word_doc_ids, theta), plates=(numDocuments * lenDocument,))


# In[8]:

words = bayespy.nodes.Categorical(bayespy.nodes.Gate(z, phi))


# In[9]:

words.observe(data)


# In[10]:

from bayespy.inference import VB


# In[11]:

theta.initialize_from_random()
phi.initialize_from_random()
z.initialize_from_random()
Q = VB(theta, phi, z, words)
Q.update(repeat=2)


# In[12]:

Q.optimize(z, collapsed=[theta, phi], maxiter=100)


# In[13]:

np.exp(phi.get_moments())


# In[14]:

np.exp(theta.get_moments())


# In[15]:

z.get_moments()

**Comment by jluttine** [comment]
Ok, glad to hear! :yum:
