### ISSUE TITLE
Axis labels not visible on Hinton diagrams

### ISSUE THREAD

**Issue by jluttine** [bayespy/bayespy#64]
To reproduce:
```python
import bayespy.plot as bpplt
bpplt.hinton([[1, 2], [3, 4]])
bpplt.pyplot.xlabel("x label")
bpplt.pyplot.ylabel("y label")
```

**Comment by chriscramer** [comment]
This appears to be an issue with turning off the axis in the _hinton plot function - no axis == no axis label.  I've made some local changes that change the default of square to False in this function.  Then instead of turning the axis off, I explicitly turn it on.  Then I explicitly call:

```python
axes.axis('image')
```

which sets the scaling to the size of the data.  The result is a nice looking hinton plot with the axes enabled, allowing me to set the axis labels.

**Comment by jluttine** [comment]
Nice! If you have made some working fixes to bayespy codebase, pull requests are obviously most warmly welcome (to develop branch). I haven't had time to take a look on this yet.

**Comment by chriscramer** [comment]
Sounds good - I wasn't sure how you worked.  I'll fork and send a pull request to develop

**Comment by jluttine** [comment]
Yep, I should write some instructions about making contributions. Thanks!
