### ISSUE TITLE
Syntax error in bayespy 

### ISSUE THREAD

**Issue by hitalex** [bayespy/bayespy#8]
When I import bayespy, I got a syntax error:

import bayespy
  File "/usr/local/lib/python2.7/dist-packages/bayespy/utils/misc.py", line 452
    def sum_multiply(*args, axis=None, sumaxis=True, keepdims=False):
                               ^
SyntaxError: invalid syntax

OS: Ubuntu 12.04 LTS
Python: 2.7
bayespy version: 0.2.3

**Comment by jluttine** [comment]
Thanks for the report! You get this error because BayesPy doesn't support Python 2. It requires Python >= 3.2 (also, recent matplotlib requires Python >= 3.3). I have supported Python 3 only, because I like some features that are not available in Python 2 (like that syntax error in Python 2). Also, it is easier to maintain only for Python 3 and not both. And by supporting Python 3 now, I don't need to make transition in near future.

However, if there is a need for Python 2 support and Python 3 is not an option, I may consider it, but probably it would be just too much work..

So, at least for now, use Python 3, preferably Python>=3.3.
